### ISSUE TITLE
Need to be able to define custom reasons for invalidation

### ISSUE THREAD

**Issue by ryanvolum** [Stevenic/botbuilder-toybox#2]
Right now each prompt either successfully validates input and returns it, or finds that that the input doesn't meet the constraints and returns the retry prompt. We need a way to return custom reasons for failure when extending prompts. This would allow us to return reasons like "nameTooLong" or "invalid zip code" to determine what retry prompt to send.

**Comment by Stevenic** [comment]
So let me ask this... I was trying to avoid baking in further validation into the prompts as that just added further complications in the v3 version of prompts. If we added the `maxRetries` option from issue #1 would it be enough to be able to wrap a prompt with another dialog that did your custom validation? 

This is basically the same issue we struggled with for prompts in v4 in general. What's the most intuitive way to extend things?
