### ISSUE TITLE
dependent lib missing

### ISSUE THREAD

**Issue by tschnoelzer** [Stevenic/botbuilder-toybox#4]
Hi team,

when using the "botbuilder-toybox-dialogs": "^0.1.0-m1.2" i am facing an error due to missing microsoft/recognizers-text-options. Reproduce easy with base example.

```
Error: Cannot find module '@microsoft/recognizers-text-options'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./projects/comboo-pack/cmb-app/server/node_modules/botbuilder-toybox-dialogs/lib/prompts/confirmPrompt.js:3:21)
```

when digging into with "npm view  @microsoft/recognizers-text-suite  dependencies" there is no dependency for recognizers-text-options.

Just saw that building from sources also has errors:

```
lerna ERR! src/fromPatch.ts(34,91): error TS2365: Operator '!==' cannot be applied to types 'string' and 'ChannelAccount | undefined'.
lerna ERR! src/showTyping.ts(5,62): error TS2305: Module '"./botbuilder-toybox/node_modules/botbuilder/lib/botbuilder"' has no exported member 'applyConversationReference'.
```

**Comment by Stevenic** [comment]
Just published updated packages.

**Comment by Stevenic** [comment]
By the way @tschnoelzer just a heads up... I'm planning to deprecate both `botbuilder-toybox-dialogs` and `botbuilder-toybox-prompts` in a week or two. The reason for that is a variant of these packages are getting pulled into the v4 SDK directly.  You should be ok using the dialogs package that's here for another week but after we publish our `m2` bits you'll want to switch. I've already made a number of improvements in the new dialogs library but it will be very similar to whats here.

An unfortunate side effect of this project is that if I actually build something useful it runs the risk of getting pulled directly into the main SDK :)
